# Generated by Django 4.1.1 on 2022-09-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharin', '0002_publicacao_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='criador',
        ),
    ]
