# Generated by Django 4.1.1 on 2022-09-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharin', '0005_alter_publicacao_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='criador',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
