# Generated by Django 4.1.1 on 2022-09-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharin', '0007_alter_publicacao_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='criador',
            field=models.IntegerField(default=1),
        ),
    ]
